# vim: ft=yaml
name: build

on:
  push:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:

jobs:
  rescue:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: >-
          sudo apt-get install --quiet --yes
            python3-ruamel.yaml
            squashfs-tools-ng
            mmdebstrap
      - run: |
          wget https://raw.githubusercontent.com/bdrung/bdebstrap/v0.4.0/bdebstrap -O bdebstrap
          chmod +x bdebstrap
      - run: |
          ./bdebstrap --force --config rescue.yml
      - uses: actions/upload-artifact@v2
        with:
          name: rescue
          path: build/rescue/*
          if-no-files-found: error
