# vim: ft=yaml
name: build

on:
  push:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
  workflow_dispatch:

jobs:
  rescue:
    name: ${{ matrix.target }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        target:
          - rescue-debian
          - rescue-ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: >
          sudo apt-get install --quiet --yes
          bdebstrap
          debian-archive-keyring
          squashfs-tools-ng
          grub-pc-bin
          grub-efi-amd64-bin
          xorriso
          mtools
      - name: Build root.squashfs
        run: make build/${{ matrix.target }}/root.squashfs
      - name: Build ISO
        run: make build/${{ matrix.target }}.iso
      - name: Upload netboot archive
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}-netboot.zip
          path: build/${{ matrix.target }}/*
          if-no-files-found: error
      - name: Upload ISO image
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}.iso
          path: build/${{ matrix.target }}.iso
          if-no-files-found: error
          archive: false
