# vim: ft=yaml
name: build

on:
  push:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
  workflow_dispatch:

jobs:
  rescue:
    name: ${{ matrix.target }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        target:
          - rescue-debian
          - rescue-ubuntu

    steps:
      - uses: actions/checkout@v5
      - run: >
          sudo apt-get install --quiet --yes
          bdebstrap
          debian-archive-keyring
          squashfs-tools-ng
      - run: make build/${{ matrix.target }}/root.squashfs
      - uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.target }}
          path: build/${{ matrix.target }}/*
          if-no-files-found: error
